// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tLambLogFieldNames          = builder.RawFieldNames(&TLambLog{})
	tLambLogRows                = strings.Join(tLambLogFieldNames, ",")
	tLambLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tLambLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tLambLogRowsWithPlaceHolder = strings.Join(stringx.Remove(tLambLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tLambLogModel interface {
		Insert(ctx context.Context, data *TLambLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TLambLog, error)
		Update(ctx context.Context, data *TLambLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTLambLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TLambLog struct {
		Id         int64     `db:"id"`          // 主键ID
		UserId     int64     `db:"user_id"`     // 用户ID
		Method     string    `db:"method"`      // 方法
		Msg        string    `db:"msg"`         // 消息
		CreateTime time.Time `db:"create_time"` // 创建时间
	}
)

func newTLambLogModel(conn sqlx.SqlConn) *defaultTLambLogModel {
	return &defaultTLambLogModel{
		conn:  conn,
		table: "`t_lamb_log`",
	}
}

func (m *defaultTLambLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTLambLogModel) FindOne(ctx context.Context, id int64) (*TLambLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tLambLogRows, m.table)
	var resp TLambLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLambLogModel) Insert(ctx context.Context, data *TLambLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tLambLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Method, data.Msg)
	return ret, err
}

func (m *defaultTLambLogModel) Update(ctx context.Context, data *TLambLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tLambLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Method, data.Msg, data.Id)
	return err
}

func (m *defaultTLambLogModel) tableName() string {
	return m.table
}
