// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tLambUserFieldNames          = builder.RawFieldNames(&TLambUser{})
	tLambUserRows                = strings.Join(tLambUserFieldNames, ",")
	tLambUserRowsExpectAutoSet   = strings.Join(stringx.Remove(tLambUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tLambUserRowsWithPlaceHolder = strings.Join(stringx.Remove(tLambUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tLambUserModel interface {
		Insert(ctx context.Context, data *TLambUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TLambUser, error)
		FindOneByLoginName(ctx context.Context, loginName string) (*TLambUser, error)
		Update(ctx context.Context, data *TLambUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTLambUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TLambUser struct {
		Id             int64          `db:"id"`              // 主键ID
		UserName       string         `db:"user_name"`       // 用户名
		LoginName      string         `db:"login_name"`      // 登录名
		LoginPassword  string         `db:"login_password"`  // 密码
		Md5Password    string         `db:"md5_password"`    // md5密码
		Email          sql.NullString `db:"email"`           // 邮箱
		TotalNumber    int64          `db:"total_number"`    // 总次数
		Remaining      int64          `db:"remaining"`       // 剩余次数
		Money          sql.NullInt64  `db:"money"`           // 金额
		ApplicationKey sql.NullString `db:"application_key"` // 请求标识
		XAppId         sql.NullString `db:"x_app_id"`        // x_app_id
		XAppKey        sql.NullString `db:"x_app_key"`       // x_app_key
		CreateTime     time.Time      `db:"create_time"`     // 创建时间
	}
)

func newTLambUserModel(conn sqlx.SqlConn) *defaultTLambUserModel {
	return &defaultTLambUserModel{
		conn:  conn,
		table: "`t_lamb_user`",
	}
}

func (m *defaultTLambUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTLambUserModel) FindOne(ctx context.Context, id int64) (*TLambUser, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tLambUserRows, m.table)
	var resp TLambUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLambUserModel) FindOneByLoginName(ctx context.Context, loginName string) (*TLambUser, error) {
	var resp TLambUser
	query := fmt.Sprintf("select %s from %s where `login_name` = ? limit 1", tLambUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, loginName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLambUserModel) Insert(ctx context.Context, data *TLambUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tLambUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserName, data.LoginName, data.LoginPassword, data.Md5Password, data.Email, data.TotalNumber, data.Remaining, data.Money, data.ApplicationKey, data.XAppId, data.XAppKey)
	return ret, err
}

func (m *defaultTLambUserModel) Update(ctx context.Context, newData *TLambUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tLambUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserName, newData.LoginName, newData.LoginPassword, newData.Md5Password, newData.Email, newData.TotalNumber, newData.Remaining, newData.Money, newData.ApplicationKey, newData.XAppId, newData.XAppKey, newData.Id)
	return err
}

func (m *defaultTLambUserModel) tableName() string {
	return m.table
}
