// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tLambPointFieldNames          = builder.RawFieldNames(&TLambPoint{})
	tLambPointRows                = strings.Join(tLambPointFieldNames, ",")
	tLambPointRowsExpectAutoSet   = strings.Join(stringx.Remove(tLambPointFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tLambPointRowsWithPlaceHolder = strings.Join(stringx.Remove(tLambPointFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tLambPointModel interface {
		Insert(ctx context.Context, data *TLambPoint) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TLambPoint, error)
		Update(ctx context.Context, data *TLambPoint) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTLambPointModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TLambPoint struct {
		Id         int64          `db:"id"`          // 主键ID
		Person     string         `db:"person"`      // 人
		Page       int64          `db:"page"`        // 页
		Stroke     int64          `db:"stroke"`      // 笔划
		Lng        float64        `db:"lng"`         // 横坐标
		Lat        float64        `db:"lat"`         // 纵坐标
		Ts         sql.NullInt64  `db:"ts"`          // 时间戳
		Pressure   sql.NullInt64  `db:"pressure"`    // 压力
		Color      sql.NullString `db:"color"`       // 颜色
		CreateTime time.Time      `db:"create_time"` // 创建时间
	}
)

func newTLambPointModel(conn sqlx.SqlConn) *defaultTLambPointModel {
	return &defaultTLambPointModel{
		conn:  conn,
		table: "`t_lamb_point`",
	}
}

func (m *defaultTLambPointModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTLambPointModel) FindOne(ctx context.Context, id int64) (*TLambPoint, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tLambPointRows, m.table)
	var resp TLambPoint
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLambPointModel) Insert(ctx context.Context, data *TLambPoint) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tLambPointRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Person, data.Page, data.Stroke, data.Lng, data.Lat, data.Ts, data.Pressure, data.Color)
	return ret, err
}

func (m *defaultTLambPointModel) Update(ctx context.Context, data *TLambPoint) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tLambPointRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Person, data.Page, data.Stroke, data.Lng, data.Lat, data.Ts, data.Pressure, data.Color, data.Id)
	return err
}

func (m *defaultTLambPointModel) tableName() string {
	return m.table
}
