// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tLinkAinFieldNames          = builder.RawFieldNames(&TLinkAin{})
	tLinkAinRows                = strings.Join(tLinkAinFieldNames, ",")
	tLinkAinRowsExpectAutoSet   = strings.Join(stringx.Remove(tLinkAinFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tLinkAinRowsWithPlaceHolder = strings.Join(stringx.Remove(tLinkAinFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tLinkAinModel interface {
		Insert(ctx context.Context, data *TLinkAin) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TLinkAin, error)
		Update(ctx context.Context, data *TLinkAin) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTLinkAinModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TLinkAin struct {
		Id         int64          `db:"id"`
		Title      string         `db:"title"`
		Link       string         `db:"link"`
		Project    string         `db:"project"`
		Type       sql.NullString `db:"type"`
		LoginName  sql.NullString `db:"login_name"`
		Password   sql.NullString `db:"password"`
		Remark     sql.NullString `db:"remark"`
		CreateTime sql.NullTime   `db:"create_time"`
		UserId     sql.NullString `db:"user_id"`
	}
)

func newTLinkAinModel(conn sqlx.SqlConn) *defaultTLinkAinModel {
	return &defaultTLinkAinModel{
		conn:  conn,
		table: "`t_link_ain`",
	}
}

func (m *defaultTLinkAinModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTLinkAinModel) FindOne(ctx context.Context, id int64) (*TLinkAin, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tLinkAinRows, m.table)
	var resp TLinkAin
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLinkAinModel) Insert(ctx context.Context, data *TLinkAin) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tLinkAinRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Link, data.Project, data.Type, data.LoginName, data.Password, data.Remark, data.UserId)
	return ret, err
}

func (m *defaultTLinkAinModel) Update(ctx context.Context, data *TLinkAin) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tLinkAinRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Link, data.Project, data.Type, data.LoginName, data.Password, data.Remark, data.UserId, data.Id)
	return err
}

func (m *defaultTLinkAinModel) tableName() string {
	return m.table
}
