// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tLinkCorporateFieldNames          = builder.RawFieldNames(&TLinkCorporate{})
	tLinkCorporateRows                = strings.Join(tLinkCorporateFieldNames, ",")
	tLinkCorporateRowsExpectAutoSet   = strings.Join(stringx.Remove(tLinkCorporateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tLinkCorporateRowsWithPlaceHolder = strings.Join(stringx.Remove(tLinkCorporateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tLinkCorporateModel interface {
		Insert(ctx context.Context, data *TLinkCorporate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TLinkCorporate, error)
		FindOneByTitle(ctx context.Context, title string) (*TLinkCorporate, error)
		Update(ctx context.Context, data *TLinkCorporate) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTLinkCorporateModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TLinkCorporate struct {
		Id         int64          `db:"id"`          // 主键
		Title      string         `db:"title"`       // 标题
		Link       string         `db:"link"`        // 链接
		Type       sql.NullString `db:"type"`        // 类型
		Project    sql.NullString `db:"project"`     // 项目
		LoginName  sql.NullString `db:"login_name"`  // 登录名
		Password   sql.NullString `db:"password"`    // 密码
		Remark     sql.NullString `db:"remark"`      // 备注
		CreateTime sql.NullTime   `db:"create_time"` // 创建时间
		UserId     sql.NullString `db:"user_id"`     // 系统用户
	}
)

func newTLinkCorporateModel(conn sqlx.SqlConn) *defaultTLinkCorporateModel {
	return &defaultTLinkCorporateModel{
		conn:  conn,
		table: "`t_link_corporate`",
	}
}

func (m *defaultTLinkCorporateModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTLinkCorporateModel) FindOne(ctx context.Context, id int64) (*TLinkCorporate, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tLinkCorporateRows, m.table)
	var resp TLinkCorporate
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLinkCorporateModel) FindOneByTitle(ctx context.Context, title string) (*TLinkCorporate, error) {
	var resp TLinkCorporate
	query := fmt.Sprintf("select %s from %s where `title` = ? limit 1", tLinkCorporateRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, title)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTLinkCorporateModel) Insert(ctx context.Context, data *TLinkCorporate) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tLinkCorporateRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Link, data.Type, data.Project, data.LoginName, data.Password, data.Remark, data.UserId)
	return ret, err
}

func (m *defaultTLinkCorporateModel) Update(ctx context.Context, newData *TLinkCorporate) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tLinkCorporateRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Title, newData.Link, newData.Type, newData.Project, newData.LoginName, newData.Password, newData.Remark, newData.UserId, newData.Id)
	return err
}

func (m *defaultTLinkCorporateModel) tableName() string {
	return m.table
}
