// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tMysqlColumnFieldNames          = builder.RawFieldNames(&TMysqlColumn{})
	tMysqlColumnRows                = strings.Join(tMysqlColumnFieldNames, ",")
	tMysqlColumnRowsExpectAutoSet   = strings.Join(stringx.Remove(tMysqlColumnFieldNames, "`bigint`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tMysqlColumnRowsWithPlaceHolder = strings.Join(stringx.Remove(tMysqlColumnFieldNames, "`bigint`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tMysqlColumnModel interface {
		Insert(ctx context.Context, data *TMysqlColumn) (sql.Result, error)
		FindOne(ctx context.Context, bigint int64) (*TMysqlColumn, error)
		Update(ctx context.Context, data *TMysqlColumn) error
		Delete(ctx context.Context, bigint int64) error
	}

	defaultTMysqlColumnModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TMysqlColumn struct {
		Bigint   int64           `db:"bigint"`
		Int0     int64           `db:"int0"`
		Smallint sql.NullInt64   `db:"smallint"`
		Tinyint  sql.NullInt64   `db:"tinyint"`
		Bit      byte            `db:"bit"`
		Decimal  sql.NullFloat64 `db:"decimal"`
		Datetime sql.NullTime    `db:"datetime"`
		Date     sql.NullTime    `db:"date"`
		Time     sql.NullString  `db:"time"`
		Char0    sql.NullString  `db:"char0"`
		Varchar  sql.NullString  `db:"varchar"`
		Text     sql.NullString  `db:"text"`
		Json     sql.NullString  `db:"json"`
		Binary   sql.NullString  `db:"binary"`
		Blob     sql.NullString  `db:"blob"`
		New      sql.NullString  `db:"new"`
	}
)

func newTMysqlColumnModel(conn sqlx.SqlConn) *defaultTMysqlColumnModel {
	return &defaultTMysqlColumnModel{
		conn:  conn,
		table: "`t_mysql_column`",
	}
}

func (m *defaultTMysqlColumnModel) Delete(ctx context.Context, bigint int64) error {
	query := fmt.Sprintf("delete from %s where `bigint` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, bigint)
	return err
}

func (m *defaultTMysqlColumnModel) FindOne(ctx context.Context, bigint int64) (*TMysqlColumn, error) {
	query := fmt.Sprintf("select %s from %s where `bigint` = ? limit 1", tMysqlColumnRows, m.table)
	var resp TMysqlColumn
	err := m.conn.QueryRowCtx(ctx, &resp, query, bigint)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTMysqlColumnModel) Insert(ctx context.Context, data *TMysqlColumn) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tMysqlColumnRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Int0, data.Smallint, data.Tinyint, data.Bit, data.Decimal, data.Datetime, data.Date, data.Time, data.Char0, data.Varchar, data.Text, data.Json, data.Binary, data.Blob, data.New)
	return ret, err
}

func (m *defaultTMysqlColumnModel) Update(ctx context.Context, data *TMysqlColumn) error {
	query := fmt.Sprintf("update %s set %s where `bigint` = ?", m.table, tMysqlColumnRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Int0, data.Smallint, data.Tinyint, data.Bit, data.Decimal, data.Datetime, data.Date, data.Time, data.Char0, data.Varchar, data.Text, data.Json, data.Binary, data.Blob, data.New, data.Bigint)
	return err
}

func (m *defaultTMysqlColumnModel) tableName() string {
	return m.table
}
