// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tRegionFieldNames          = builder.RawFieldNames(&TRegion{})
	tRegionRows                = strings.Join(tRegionFieldNames, ",")
	tRegionRowsExpectAutoSet   = strings.Join(stringx.Remove(tRegionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tRegionRowsWithPlaceHolder = strings.Join(stringx.Remove(tRegionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tRegionModel interface {
		Insert(ctx context.Context, data *TRegion) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TRegion, error)
		Update(ctx context.Context, data *TRegion) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTRegionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TRegion struct {
		Id         int64          `db:"id"`          // 主键ID
		Text       string         `db:"text"`        // 名称
		AreaCode   int64          `db:"area_code"`   // 区域码
		Lng        float64        `db:"lng"`         // 横坐标
		Lat        float64        `db:"lat"`         // 纵坐标
		RegionRank sql.NullInt64  `db:"region_rank"` // 级别
		Type       sql.NullInt64  `db:"type"`        // 类型
		ParentCode sql.NullInt64  `db:"parent_code"` // 父码
		Boundary   sql.NullString `db:"boundary"`    // 边界
		CreateTime time.Time      `db:"create_time"` // 创建时间
		Level      sql.NullInt64  `db:"level"`
	}
)

func newTRegionModel(conn sqlx.SqlConn) *defaultTRegionModel {
	return &defaultTRegionModel{
		conn:  conn,
		table: "`t_region`",
	}
}

func (m *defaultTRegionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTRegionModel) FindOne(ctx context.Context, id int64) (*TRegion, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tRegionRows, m.table)
	var resp TRegion
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTRegionModel) Insert(ctx context.Context, data *TRegion) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tRegionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Text, data.AreaCode, data.Lng, data.Lat, data.RegionRank, data.Type, data.ParentCode, data.Boundary, data.Level)
	return ret, err
}

func (m *defaultTRegionModel) Update(ctx context.Context, data *TRegion) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tRegionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Text, data.AreaCode, data.Lng, data.Lat, data.RegionRank, data.Type, data.ParentCode, data.Boundary, data.Level, data.Id)
	return err
}

func (m *defaultTRegionModel) tableName() string {
	return m.table
}
