// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTradeStockFieldNames          = builder.RawFieldNames(&TTradeStock{})
	tTradeStockRows                = strings.Join(tTradeStockFieldNames, ",")
	tTradeStockRowsExpectAutoSet   = strings.Join(stringx.Remove(tTradeStockFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTradeStockRowsWithPlaceHolder = strings.Join(stringx.Remove(tTradeStockFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tTradeStockModel interface {
		Insert(ctx context.Context, data *TTradeStock) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTradeStock, error)
		Update(ctx context.Context, data *TTradeStock) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTradeStockModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TTradeStock struct {
		Id                int64           `db:"id"`
		Code              string          `db:"code"`
		Name              sql.NullString  `db:"name"`
		Market            sql.NullString  `db:"market"`
		Price             sql.NullFloat64 `db:"price"`
		TotalValue        sql.NullInt64   `db:"total_value"`
		CirculationMarket sql.NullInt64   `db:"circulation_market"`
		CreateTime        sql.NullTime    `db:"create_time"`
	}
)

func newTTradeStockModel(conn sqlx.SqlConn) *defaultTTradeStockModel {
	return &defaultTTradeStockModel{
		conn:  conn,
		table: "`t_trade_stock`",
	}
}

func (m *defaultTTradeStockModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTTradeStockModel) FindOne(ctx context.Context, id int64) (*TTradeStock, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTradeStockRows, m.table)
	var resp TTradeStock
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTradeStockModel) Insert(ctx context.Context, data *TTradeStock) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, tTradeStockRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Name, data.Market, data.Price, data.TotalValue, data.CirculationMarket)
	return ret, err
}

func (m *defaultTTradeStockModel) Update(ctx context.Context, data *TTradeStock) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTradeStockRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Code, data.Name, data.Market, data.Price, data.TotalValue, data.CirculationMarket, data.Id)
	return err
}

func (m *defaultTTradeStockModel) tableName() string {
	return m.table
}
