// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTradeForecastFieldNames          = builder.RawFieldNames(&TTradeForecast{})
	tTradeForecastRows                = strings.Join(tTradeForecastFieldNames, ",")
	tTradeForecastRowsExpectAutoSet   = strings.Join(stringx.Remove(tTradeForecastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTradeForecastRowsWithPlaceHolder = strings.Join(stringx.Remove(tTradeForecastFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tTradeForecastModel interface {
		Insert(ctx context.Context, data *TTradeForecast) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTradeForecast, error)
		Update(ctx context.Context, data *TTradeForecast) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTradeForecastModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TTradeForecast struct {
		Id           int64           `db:"id"`
		Code         sql.NullString  `db:"code"`
		Date         sql.NullTime    `db:"date"`
		Price        sql.NullFloat64 `db:"price"`
		PredictPrice sql.NullFloat64 `db:"predict_price"`
		DiffPrice    sql.NullFloat64 `db:"diff_price"`
		TurnoverRate sql.NullFloat64 `db:"turnover_rate"`
	}
)

func newTTradeForecastModel(conn sqlx.SqlConn) *defaultTTradeForecastModel {
	return &defaultTTradeForecastModel{
		conn:  conn,
		table: "`t_trade_forecast`",
	}
}

func (m *defaultTTradeForecastModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTTradeForecastModel) FindOne(ctx context.Context, id int64) (*TTradeForecast, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTradeForecastRows, m.table)
	var resp TTradeForecast
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTradeForecastModel) Insert(ctx context.Context, data *TTradeForecast) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, tTradeForecastRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Date, data.Price, data.PredictPrice, data.DiffPrice, data.TurnoverRate)
	return ret, err
}

func (m *defaultTTradeForecastModel) Update(ctx context.Context, data *TTradeForecast) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTradeForecastRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Code, data.Date, data.Price, data.PredictPrice, data.DiffPrice, data.TurnoverRate, data.Id)
	return err
}

func (m *defaultTTradeForecastModel) tableName() string {
	return m.table
}
